plugins:
    - jekyll-seo-tag
    - jekyll-github-metadata
    - jekyll-redirect-from
    - jekyll-sitemap

theme: jekyll-theme-minimal
    
url           : "https://infominer.id/bitcoin-history"
baseurl       : "/bitcoin-history"
title         : "Bitcoin Historical Index"
description   : "The History Surrounding Bitcoin, including Pre-History and Immediately Related Fields."
author        : "⧉ Infominer"
logo          : "https://infominer.id/android-chrome-256x256.png"
repository    : "infominer33/bitcoin-history"
github        : [metadata]
rooturl       : "https://infominer.id/bitcoin-history"


twitter:
  site        : "infominer33"
  title       : "Bitcoin Historical Index"
  description : "The History Surrounding Bitcoin, including Pre-History and Immediately Related Fields."
  image       : "https://infominer.id/android-chrome-256x256.png"
  card        : "summary"
 
google_analytics: UA-132558656-1